### ISSUE TITLE
🎨 Landing Page

### ISSUE THREAD

**Issue by damla** [damla/connEth#2]
# To-Do List

Create a simple, non-scrollable landing page.

- [x] Add Sign In button for wallet authentication.
- [ ] Inform user about the features dApp has.
- [ ] Inform mobile and non Metamask users about restrictions on viewing the dashboard.
